pytest_operator/plugin.py
setup.py
tests/test_pytest_operator.py
tox.ini

Add helpers for building multiple charms and rendering bundles using those charms and other contexts. Also includes a `wait_for_bundle` helper as a starting point for replacing `juju-wait` something built-in to libjuju.
Note: This is failing currently because there still seems to be an issue with libjuju deploying bundles which reference local `.charm` files (rather than directories).

Add helpers for working with bundles

---

pytest_operator/plugin.py
tests/test_pytest_operator.py
tox.ini

[libjuju PR #470](https://github.com/juju/python-libjuju/pull/470) is still pending review, but until it lands, we can use it in the tests at least.
(Note, though, while in theory we should be able to [use `dependency_links` in `setup.py`](https://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi) to make the branches work on install, but for some reason when I tried that it didn't work.)

Switch to Juju branch with fix for .charm files in bundle and up-ported helper

---

.github/workflows/tests.yaml
setup.py
tox.ini

The upstream fixes for libjuju and charm-tools have been released, so this removes the branch workarounds in the tox.ini and updates the version in setup.py for a new release.

Remove workaround branches from tox and update version

---

.github/workflows/tests.yaml
pytest_operator/__init__.py
pytest_operator/plugin.py
pytest_operator/shims.py
setup.py
tests/test_pytest_operator.py

This refactors how the async tests are run to allow for all the tests in a given class to share the same model. Neither the newer unittest nor the older asynctest supported this, so I had to resort to managing the event loop in the class-scoped fixture and wrapping the async test methods in a sync wrapper which used run_until_complete to execute the async test methods.

Use one model per test class

---

pytest_operator/plugin.py
tox.ini

Add logging messages to model setup / cleanup and charm building, and shorten model name to just the class name plus a random suffix.

Add logging and shorten model name

---

.github/workflows/tests.yaml
.gitignore
pytest_operator/plugin.py
tests/test_pytest_operator.py

To aid in debugging failed tests, the model status will be dumped in a format similar to `juju status`, as well as the results of running `juju debug-log --replay --level=ERROR`.
Also adds a method and decorator to abort subsequent test methods if a given test method fails.

On test failure, dump model status and errors from Juju log

---

pytest_operator/plugin.py

Testing this for a Container charm the operator fails on the log line because there is no Machine for container units. I have tests this to work on a new charm and can deploy and remove the model as expected. I'm not sure if this is the only place, but I think the other instances are protected by loops which will simply not happen with no machine.
I ran black and import ordering was rearranged. I can probably revert that if it matters.

Skip machine logging for K8s

---

pytest_operator/plugin.py

I can't find any way for plugins to choose their order of loading. You can monkey patch the asyncio plugin from the operator plugin though.

Override event_loop from asyncio

---

pytest_operator/plugin.py

This is useful in tests from time to time, so it should be public.

Make ops_test.run public

---

pytest_operator/plugin.py
setup.py
tests/test_pytest_operator.py
tox.ini

Removes PyPI dependency for `charm` and `charmcraft` tools and instead relies on them being installed at the system level, ideally as snaps.
In order to work with the confinement of the `charmcraft` snap, the temp dirs have to be relocated to live under the Tox environment temp dir. It also turns out that the `check_deps` fixture wasn't working as expected, so it was fixed, as well as the need to call `charm build` without the hyphen to support the snap.
As a bit of a drive-by, this also suppresses the DeprecationWarnings generated by libjuju which are already being [tracked there][libjuju#461].
Fixes #13
Depends on charmed-kubernetes/actions-operator#9 (the integration test will fail with a "missing dependency" error until that is merged)
[libjuju#461]: …

Use snaps for charm and charmcraft

---

pytest_operator/plugin.py

If not building legacy charms, the `charm` dependency isn't actually needed, so we can defer checking it until it is required.
Fixes #18

Defer checking charm dependency

---

README.md
docs/reference.md
pytest_operator/plugin.py

Ideally these would be auto-generated from the Python code and doc-strings, but I couldn't come up with a clean way to do that.

Add reference docs

---

pytest_operator/plugin.py
tests/test_pytest_operator.py

Fix handling of charms built with `charmcraft` since the 1.1.0 release, which both switched to LXD containers for doing the build (leading to issues with referenced local files such as built libraries) as well as changed the name of the built `.charm` file to include info about the OS, series, and arch.
Fixes #23

Fix charm building for charmcraft 1.1.0

---

.github/workflows/tests.yaml
pytest_operator/plugin.py

With the latest changes in the charmcraft snap it is required to execute charmcraft in the lxd user group.

Execute charmcraft build with lxd group

---

pytest_operator/plugin.py

Charmcraft occasionally can create files in `./build` that are owned by another user.  These files cause the pytest-operator to raise an exception when cleaning up `./build`.  I have not been able to make a reproducible example to post as a bug in charmcraft, but as a mitigation added a handler here to warn on the failed deletions rather than fail entirely.

feat: gracefully handle un-deletable files in ./build

---

pytest_operator/plugin.py

Since `charmcraft` and `snapcraft` are aligning their semantics, the `build` subcommand is (or will soon be) actually only a partial step of the full charm creation process rather than the full process. Move to use `charmcraft pack` as the intended main entry-point instead.

Switch to `charmcraft pack`

---

pytest_operator/plugin.py
tests/test_pytest_operator.py

Charmcraft builds charms in LXD containers by default, but there are currently some bugs related to that and it's also less efficient if you're already running in an ephemeral environment (e.g., a GH Workflow runner). So this adds a flag to allow for skipping that by passing through the `--destructive-mode` flag.

Add flag for destructive mode builds

---

.github/workflows/tests.yaml
pytest_operator/plugin.py
tests/integration/test_pytest_operator.py
tests/unit/test_pytest_operator.py
tox.ini

When using destructive mode, or if the user is already a member of the lxd group, then using `sg` to gain the group is unnecessary and can sometimes lead to issues. Even when needed, if the group is not available, the error message produced is confusing.
This also refactors the tests into separate unit and integration tests, and updates the `abort_on_fail` autouse fixture to avoid creating an `ops_test` instance (and thus creating a model) when not needed.

Improve handling of lxd group management

---

tests/data/charms/operator-framework/charmcraft.yaml

Per https://github.com/canonical/charmcraft/issues/551 and https://discourse.charmhub.io/t/install-or-update-python-packages-before-packing-a-charm/5158, we need charmcraft to update setuptools before installing the rest of the requirements in order to prevent a failure during the install of jinja2.

Fix failure to build operator-framework test charm

---

.gitignore
pytest_operator/plugin.py
tests/integration/test_pytest_operator.py
tests/unit/test_pytest_operator.py
tox.ini

- add crash-dump option
- add function to trigger `juju-crashdump` if command is available
- fix deprecation warnings around pytest
- add unit and integration tests

Add crash-dump option to generate juju-crashdump

---

pytest_operator/plugin.py

Adds a log message so it is clear that the operator is building/deploying a bundle.  
This came up when debugging a charm where CI appeared to hang on 
```
INFO     pytest_operator.plugin:plugin.py:440 Connecting to model uk8sx:kubeflow
```
when actually it had successfully connected to the model and instead silently got stuck in a `deploy_bundle()` call.  This message adds clarity for those situations.

feat: Add log message to deploy_bundle

---

pytest_operator/plugin.py

Recreating PR since lats one did not trigger GH action to test workflow.

Add elapsed time log to key steps (#59)

---

tests/data/charms/operator-framework/charmcraft.yaml
tests/data/charms/operator-framework/requirements.txt
tests/data/test_lib/setup.py
tests/integration/test_pytest_operator.py

Use dumb test-lib instead of building pytest_operator as a library in
integration test. This will reduce the time of integration tests.

Replace build pytest_operator with test_lib

---

docs/reference.md
pytest_operator/plugin.py
tests/unit/conftest.py
tests/unit/test_pytest_operator.py

This will allow you to skip all functions marked with the `abort_on_fail`
marker, which represents bundle/charm deployment.

Adding option --no-deploy

---

docs/reference.md
pytest_operator/plugin.py
tests/integration/test_pytest_operator.py

I forgot to add the `--no-crash-dump` and `--crash-dump-output` parameters to the documentation.
I've also fixed the ability to disable running `juju-crashdump` with the `--no-crash-dump` parameter.

Updated docs for `--crash-dump` and `--crash-dump-output` parameter

---

pytest_operator/plugin.py

This sets more explicit language for the log message emitted by `build_charm`.  Previously, if a charm build failed the user would see a message like:
```
INFO     pytest_operator.plugin:plugin.py:591 Charm build for minio completed with return code 1 in 47.04s
FAILED
```
This could be ambiguous as it implies the build succeeded in X seconds, when instead it finished (with error) in X seconds.  This commit clarifies that language

fix: clarify language in build_charm logging

---

pytest_operator/plugin.py
tests/unit/test_pytest_operator.py

Moved `no-deploy` parameter check from pytest_addoption function
to pytest_load_initial_conftests.
test_run: https://pastebin.ubuntu.com/p/4ypnsdg79p/
fixes: #65

fix `no-deploy` parameter check

---

pytest_operator/plugin.py
setup.py
tox.ini

when tearing down machines which may already be gone from libjuju model, a `DeadEntityException` can be raised by libjuju.  These are safely ignore-able in this situation

Reintroduce 'DeadEntityException' allowance 

---

pytest_operator/plugin.py
setup.py

Addressing https://github.com/charmed-kubernetes/pytest-operator/issues/75
Every connection to the juju controller must also be closed, otherwise the event_loop will have connection tasks which aren't cleaned up by the async portions of websocket and python-libjuju libraries. 
Whenever a new model is added, a new connection is opened
Whenever a `Controller.connect()` method is called, a new connection is opened. 
the `_add_model(...)` method was opening a connection to a controller which wasn't cleaned up during the `_setup_model(...)` method.

Address destroying all connections to the juju controller.

---

docs/reference.md
pytest_operator/plugin.py
tests/integration/test_pytest_operator.py

added a utility to OpsTest to temporarily set "update-status-hook-interval" to a given value, and then set it back to whatever it was before (or another 'slow' value).
Solves #78

Fast forward util

---

pytest_operator/plugin.py

There are opportunities where one may need a build script which doesn't need `sudo` access to build. Lets make this optional

Allow resource scripts to be run without sudo

---

pytest_operator/plugin.py
tests/unit/test_pytest_operator.py
tox.ini

* tox 4.x requires multi-line commands to have careful line-termination in alignment with spaces in a command
* fix argument name in `ops_test.arch_specific_resources`
* mark a unit test as `async`  since it depends on an async fixture

unit tests to passing with tox 4.x

---

.github/workflows/tests.yaml
docs/reference.md
pytest_operator/plugin.py
tests/unit/conftest.py
tests/unit/test_pytest_operator.py
tox.ini

Addressing https://github.com/charmed-kubernetes/pytest-operator/issues/92 and providing a way to not necessarily use the `TOX_ENV_DIR` to host temporary files. 
There are circumstances when the `juju` snap needs to write files, but cannot use the `TOX_ENV_DIR` path because it's not under the user's `$HOME` directory. 
This change will honor `TMPDIR` first before `TOX_ENV_DIR`

break requirement on `TOX_ENV_DIR` to create temporary directories

---

.github/workflows/tests.yaml
docs/reference.md
pytest_operator/plugin.py

It is natural to just `await ops_test.forget_model()`, but that would error:
```
TypeError: OpsTest.forget_model() missing 1 required positional argument: ...
```
Use `self.current_alias` as default, instead, so passing it wouldn't be necessary.
Note: PyCharm made some whitespace fixes automatically :)
opened to replace https://github.com/charmed-kubernetes/pytest-operator/pull/104

Use current alias as default alias for `forget_model`

---

docs/reference.md
pytest_operator/plugin.py

When [charms fail to build in CI](https://github.com/canonical/traefik-k8s-operator/actions/runs/4457784790/jobs/7829062070#step:5:891), all we see is 
```
RuntimeError: Failed to build charm .:
Packing the charm.
Launching environment to pack for base name='ubuntu' channel='20.04' architectures=['amd64'] (may take a while the first time but it's reusable)
Packing the charm
Packing the charm.
Building charm in '/root'
Running step PULL for part 'charm'
Running step OVERLAY for part 'charm'
Running step BUILD for part 'charm'
Parts processing error: Failed to run the build script for part 'charm'.
Failed to build charm for bases index '0'.
Full execution log: '/home/runner/.local/state/charmcraft/log/charmcraft-20230319-020431.474806.log'
```
It could be handy to temporarily (or …

Add verbosity flag to build_charm

---

pytest_operator/plugin.py

With the advent of charmcraft's reactive plugin, it's now possible to build reactive charms using charmcraft.
Allows the pytest-operator framework to choose this option if a layer.yaml and charmcraft.yaml are both present.

build reactive charms with charmcraft if a charmcraft.yaml file is present

---

docs/reference.md
pytest_operator/plugin.py
tests/unit/test_pytest_operator.py

This PR adds new controls over whether pytest-operator outputs a juju crashdump.  Previously, the crashdump was output only if tests failed and `--keep-models==False`.  This commit adds additional modes:
* always: dumps after all tests
* on-failure: dumps after failed tests
* legacy: (DEFAULT) dumps after a failed test if --keep-models is False
* never: never dumps

feat: expand on options for calling juju crashdump

---

pytest_operator/plugin.py

Support passing `destroy_storage=True` to `OpsTest.forget_model`.
This is useful for tearing down models that are provisioning storage.

support destroy_storage when forgetting models

---

.github/workflows/tests.yaml
docs/reference.md
pytest_operator/plugin.py
tests/unit/test_pytest_operator.py
tox.ini

In response to the feature requested 
* https://github.com/charmed-kubernetes/pytest-operator/issues/110
If the `--model=<name>` switch is used with this plugin,  
* if that model doesn't exist -- create and keep that model after the tests
* reuse any existing model by this name
This should prevent errors like this when `--model=testing` is specfiied
```
juju.errors.JujuConnectionError: Model not found: admin/testing
```

When model switch is used, reuse or create and keep that model

---

pytest_operator/plugin.py
tests/unit/test_pytest_operator.py

reading of the provided model-config was dropped in a previous refactor.  Adding that back in
Addresses https://github.com/charmed-kubernetes/pytest-operator/issues/117

Re-introduce model-config

---

pytest_operator/plugin.py

When `charmcraft.yaml` has multiple bases, then multiple *.charm files are created.
Before this PR, `build_charm` kept only one charm file:
```
find . -type f -name "*.charm"
./.tox/integration/tmp/pytest/test-juju-info-l4uc0/charms/grafana-agent_ubuntu-20.04-amd64.charm
```
With this PR we'd keep all *.charm files.
```
find . -type f -name "*.charm" 
./.tox/integration/tmp/pytest/test-juju-info-9fz20/charms/grafana-agent_ubuntu-20.04-amd64.charm
./.tox/integration/tmp/pytest/test-juju-info-9fz20/charms/grafana-agent_ubuntu-22.04-amd64.charm
```
Usage example:
- https://github.com/canonical/grafana-agent-operator/pull/9

Keep all packed charms, if there are more than one

---

pytest_operator/plugin.py

Charmcraft has been updated to read metadata information directly from the `charmcraft.yaml` file without a separate `metadata.yaml`. Update to `pytest-operator` to read metadata information from `charmcraft.yaml` when required. 
For further details, refer to the pull request https://github.com/canonical/charmcraft/pull/1126.

Enable reading charm name from charmcraft.yaml

---

docs/reference.md
pytest_operator/plugin.py
setup.py
tests/unit/test_pytest_operator.py

Adds new `--crash-dump-args` as extra arguments to pass to `juju-crashdump`

Allow taking a crashdump with extra arguments

---

docs/reference.md
pytest_operator/plugin.py
setup.py
tests/unit/test_pytest_operator.py

introduce Enumerations to preserve or destroy various tracked models

Improvements in keeping or destroying models

---

.github/workflows/tests.yaml
tests/data/charms/reactive-framework/wheelhouse.txt

* Test with juju 2.9, 3.1, and 3.3
* Also use `charm-channel` `3.x/stable` to properly build reactive charms
* Pin sniffio<1.3.0 because after 2 years this dep finally decided it hated old `setuptools`
* archive built charms in the event that the tests fail

Move integration tests to juju 2.9, 3.1, and 3.3

---

.github/workflows/tests.yaml
.gitignore
pytest_operator/plugin.py
tests/data/test_lib/setup.py
tests/integration/test_add_k8s.py
tests/integration/test_opstest_add_k8s.py
tests/integration/test_pytest_operator.py
tests/unit/test_pytest_operator.py
tox.ini

* pytest operator supports `add_k8s()` method
* tears down the clouds first, tearing down any models on those clouds first
* tears down any other models last in reverse order they are created
* allows creation of a k8s cloud given a `kubernetes.client.configuration.Configuration`
* supports `add-k8s` arguments like `context`,  `skip_storage` and `storage_class`
* see `test_opstest_add_k8s.py` for example of how to use until I can get documentation into this
* uses updated inclusivity workflow check

Produce apis to add a k8s cloud and tear down its models first

---

README.md

Fix reference docs link in readme, so that it shows correctly on PyPI.
Since readme content is copied, PyPI doesn't know the base URL for the links in the readme file, and today pypi's link for "the reference docs" points to `https://pypi.org/project/pytest-operator/docs/reference.md` which doesn't exit.

docs: fix reference docs link in readme

---

docs/reference.md
pytest_operator/plugin.py
tests/unit/test_pytest_operator.py

Adds a `--destroy-storage` CLI argument to enable destroying the storage allocated by Juju on the created models. Without this feature, it is not possible to automatically cleanup storage allocated during the test suite as part of the teardown process.
The behavior is opt-in and can be overridden in a per model basis in a way that resembles the `--keep-models` argument behavior. 
Closes #132

Add destroy-storage command line parameter

---

.github/workflows/tests.yaml
tests/integration/test_pytest_operator.py

Rather the follow a specific latest 3.* snap channel, just rolling pick the latest juju stable from the 3/stable branch
* ends testing of 3.3/stable juju specifically in favor of whatever is the most recent juju 3.* version
* update actions workflows
* provides more time for the setup of the models

Bump juju charm versions to follow 3/stable

---

.github/workflows/tests.yaml
pytest_operator/plugin.py
tests/unit/test_pytest_operator.py

Addresses issue #139 on ubuntu-24.04 workers
* tests on broader versions of ubuntu runners
* fixes unit test issue created by newer websockets library
* the new ubuntu-24.04 tests fail because of https://github.com/charmed-kubernetes/actions-operator/issues/82 but i cannot fix it without this change first.

Use sudo rather than sg on ubuntu-24.04 runners

---

pytest_operator/plugin.py

#141 describes a too complicated api for build_charm
Address by removing some complexity in the API and providing better method docs for what happens when your charm fails to build

Simplify typing on build_charm method

---

docs/reference.md
pytest_operator/plugin.py
setup.py
tests/unit/test_pytest_operator.py

Allows one to direct pytest to run with new arguments for charmcraft
* `--charmcraft-args` can be used multiple times to pass extra args to charmcraft

feat: Adds charmcraft pack arguments

---

docs/reference.md
pytest_operator/plugin.py
setup.py
tests/unit/test_pytest_operator.py

`charmcraft pack` can yield multiple charm files in the event there are multiple runs on or multiple platforms. 
By passing `return_all=True`, the `build_charm` method returns a list of those paths.

Support for multiple charm files outputs during charmcraft pack

---

pytest_operator/plugin.py

There is a small documentation issue where a parameter is misnamed.
This PR fixes that.

fix: Small documentation issue

---

pytest_operator/plugin.py
setup.py
tests/integration/test_pytest_operator.py

The current implementation of fast-forward fails to restore the slow interval if an exception was raised in the context manager.
This implementation is safer in that regard as it will restore the slow interval no matter what.
Closes: #137

feat: Always restore slow interval after fast-forward

---

pytest_operator/plugin.py

The logs when build_charm fails are currently unclear. For example, in the context of a `tox` integration test:
It is not clear that the final line of output is the stderr of the charm-building command, nor is it clear what command was used to attempt building the charm. It is rather difficult to troubleshoot starting from just this information.
With the suggested changes, it is considerably easier to get started with troubleshooting:

improve build_charm failure logs

---

pytest_operator/plugin.py

Found in a PR where multiple kubernetes clouds were created by pytest_operator atop an existing machine cloud. 
When cleaning up the created clouds, we deleted an entry in `self.forget_cloud(...)`  that was maintained by `self._clouds`
this results in an exception:
```
File "/home/ubuntu/actions-runner/_work/k8s-operator/k8s-operator/.tox/integration/lib/python3.12/site-packages/pytest_operator/plugin.py", line 1092, in _cleanup_models
for cloud in reversed(self._clouds):
RuntimeError: OrderedDict mutated during iteration
```
The correct behavior is to operate on an inline list instead of iterating the dict itself.

fix: cloud entries in an dictionary were being deleted while iterating the object
